sudo: required
rvm:
  - 2.2

before_script:
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec spec

deploy:
  provider: heroku
  app: rocky-sands-79934
  api_key:
    secure: Zs2+jUAJ0wLOhkOUzvokg3OBGNsKxiEYVNG6bkIluje+iJQ9RkW9/JMuo4BT4ksfRyEob634eOWJrX6Tk8aj7R4qmDTFlzPDynDfgJFV3V3aR87Tq0N03CJmOctdy9l56JK90NW7vAotuQu2dvYOUfe6NJa88fPsgbuUTlrvncLKw+DySb0exhodf2E2iWbE+dx3EUQvbxq4t8lhEKBOMMJw6ZDdUvH/GVWX2AfeiWENAxh3LBUw+GcU8vYcMTeLoRxbXl4B1kTuZRZcuqKlqicB698cbvSw8BCl+oeBcOcIv37TS12uyflyo2Ftvh4XgopdTITlIDMens0aTT8mrKYgPE8bjSN4p8QiM6p6cZLJZ0Trpo/349hg8ivrRvaC5eO+edLqiCEz3xuLaJBFz4Lbtpq4MjU8yUp2Uo0Yl0rPCXiDLpvNiOW6Vlo6QnxGK8JMpXE8Pkbrw4zIpmEqmXi5SziteUvGl8rLAPtagE6dkmY48dIkhf3IB446I9GrsBezwJJOd4XuHwCbBezzOZnToFEKb0yqnVi/gPEzEYu1emYPE6lopkJ931YtJVqN5W1CLTVNgf8TZPhhPcDxju8T+BpuyT9K+hfkp7NoD1ysduc9rAVgJeDb98y3zw9B7R7crwVSw28wfdJinw9FcaadTQfpZS50dnQIjYU2oA4=
  run:
    - rake db:migrate
